---
- name: DEPLOY AS3 DEC
  hosts: localhost
  connection: local
  gather_facts: no


  vars:
    uri_method: POST
  
  vars_files:
    - ../Creds/big_creds.yaml

  tasks:
    - name: Deploy an AS3 Declaration
      uri:
        url: https://20.39.162.40/mgmt/shared/appsvcs/declare
        user: "{{ bigip_user }}"
        password: "{{ bigip_pass }}"
        method: "{{ uri_method }}"
        body: "{{ lookup('file','AS3_Declaration.json') }}"
        force_basic_auth: yes
        status_code: 200
        body_format: json
        validate_certs: no
      register: as3_response

    - name: DEBUG OUTPUT AS3 RESPONSE
      debug:
        msg: "{{as3_response}}"   
    - name: DEBUG OUTPUT AS3 RESPONSE
      debug:
        msg: "Content Length = {{as3_response.content_length}}"
...